version: '3.8'

services:
    app:
        build:
            context: ./docker/php
        container_name: laravel_app
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - redis
            - rabbitmq
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

    rabbitmq:
        image: rabbitmq:3-management
        container_name: laravel_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - laravel

    node:
        image: node:18-alpine
        container_name: laravel_node
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: sh -c "yarn install && yarn dev"
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
